/**
 * Real Sample Legal Notice Content
 * Based on actual professional notices from VakilTech production cases
 * Content is masked for privacy but maintains professional structure
 */

import type { SampleNoticeContent } from "@/components/legal-notice/SampleNoticeModal";

export const realSampleNotices: Record<string, SampleNoticeContent> = {
  "money-recovery": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR RECOVERY OF LOAN AMOUNT OF ₹25,000/-",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr./Ms. ████████",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Recovery of Loan Amount of ₹25,000/-",
      "",
      "Sir/Madam,",
      "",
      "I, the undersigned advocate, have been instructed by my client to address this legal notice to you under Section 138 of the Bharatiya Nagarik Suraksha Sanhita, 2023.",
      "",
      "My client states that he is a well-reputed, law-abiding, and responsible individual, known for his integrity and upright conduct in both personal and professional spheres.",
      "",
      "My client states that both of you are related to each other and have shared a cordial relationship founded upon mutual trust, respect, and goodwill. My client has always treated you with the utmost regard and extended help, support, and cooperation whenever required.",
      "",
      "My client states that you approached him in financial distress, seeking a loan of ₹25,000/- (Rupees Twenty Five Thousand Only) for personal purpose. Relying upon the cordial relationship shared with you and in good faith, my Client acceded to your request and extended financial assistance. The said sum was advanced to you on ████████, which stands acknowledged by you without demur.",
      "",
      "My client states that at the time of availing the aforesaid loan, you categorically and unequivocally assured him that the entire loan amount would be repaid within a few days, as you were anticipating some payments on your end.",
      "",
      "My client states that your continued failure and deliberate refusal to return the outstanding dues squarely amounts to cheating and fraudulent conduct. Your repeated misrepresentations, false assurances, and intentional withholding of repayment clearly demonstrate mala fide intention from the very inception of the transaction.",
      "",
      "Such conduct clearly constitutes fraud, cheating, and criminal breach of trust, which are criminal offences punishable under Section 316 of the BNS, 2023 (Cheating and dishonestly inducing delivery of property), Section 336 of the BNS, 2023 (Criminal breach of trust), and Section 418 of the BNS, 2023.",
      "",
      "DEMANDS:",
      "1. Pay the sum of ₹25,000/- (Rupees Twenty Five Thousand Only) immediately",
      "2. A further sum of ₹10,000/- towards compensation for mental agony and harassment",
      "3. ₹5,000/- towards legal notice costs",
      "4. Total sum payable: ₹40,000/- with 12% interest per annum",
      "",
      "You are hereby called upon to pay the aforesaid amount within 7 days from receipt of this notice, failing which my client shall be constrained to initiate appropriate civil and criminal proceedings against you at your risk, cost, and consequences.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  "cheque-bounce": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE UNDER SECTION 138 OF NEGOTIABLE INSTRUMENTS ACT, 1881",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr./Ms. ████████",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Notice for Cheque Bounce under Section 138 of Negotiable Instruments Act",
      "",
      "Sir/Madam,",
      "",
      "Under instructions from my client, I, the undersigned advocate, hereby serve upon you this Legal Notice under Section 138 of the Negotiable Instruments Act, 1881, and put you to notice of the following facts:",
      "",
      "My client states that you approached him seeking financial assistance of ₹6,40,000/- (Rupees Six Lakh Forty Thousand Only) for purchasing a property. Upon your repeated requests and assurances of timely repayment, my client transferred the said amount to your bank account on ████████.",
      "",
      "However, it later came to light that the property in question did not belong to you. Upon confronting you regarding this wrongdoing, you admitted to the same and agreed to refund the amount.",
      "",
      "To discharge your liability, you issued Cheque No. ████████ drawn on ████ BANK LTD, ████████ branch dated ████████ for a sum of Rs. 6,40,000/- (Rupees Six Lakh Forty Thousand Only) from your Bank Account No. ████████.",
      "",
      "However, when the abovementioned cheque was presented for clearing, the same was returned dishonored on ████████ with the reason 'FUNDS INSUFFICIENT'. This was brought to my client's notice through cheque return memo issued by ████ Bank Ltd.",
      "",
      "The dishonour of the said cheque constitutes an offence under Section 138 of the Negotiable Instruments Act, 1881, which makes it a criminal offence to issue a cheque that is dishonoured for insufficiency of funds. The offence is punishable with imprisonment for a term up to two years, or with fine up to twice the amount of the cheque, or both.",
      "",
      "DEMAND:",
      "You are hereby called upon to make payment of the cheque amount Rs. 6,40,000/- (Rupees Six Lakh Forty Thousand Only) within 15 days of receipt of this legal notice.",
      "",
      "Take notice that if you fail to make payment within the stipulated period of 15 days, my client shall be constrained to initiate criminal proceedings under Section 138 of the Negotiable Instruments Act, 1881 before the appropriate Magistrate, and you shall be liable for prosecution and punishment as per law.",
      "",
      "This Notice is issued without prejudice to all other rights and remedies available to my client under law.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "Enrolment No: D/████/20██",
      "On behalf of My Client",
    ],
  },

  "outstanding-payment": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR RECOVERY OF OUTSTANDING PAYMENT OF ₹5,00,000/-",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "M/s ████ Private Limited",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Recovery of Outstanding Business Payment",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client M/s ████████ Pvt. Ltd., I, the undersigned advocate, hereby serve upon you this Legal Notice demanding payment of outstanding dues.",
      "",
      "My client states that they entered into a business agreement with your company dated ████████ for supply of ████████ [goods/services] as per the terms and conditions mutually agreed upon.",
      "",
      "My client has duly performed all obligations under the agreement including timely delivery of goods/services as per agreed specifications and quality standards. The total invoice value amounts to ₹5,00,000/- (Rupees Five Lakh Only) as per Invoice No. ████████ dated ████████.",
      "",
      "As per the payment terms agreed in the contract, payment was due within 30 days from the date of invoice i.e., by ████████. However, despite repeated reminders, follow-ups, and communications sent via email and phone calls, your company has willfully and deliberately defaulted on making the payment.",
      "",
      "Your continued non-payment has caused severe financial hardship and business disruption to my client, affecting their working capital, operational expenses, and business credibility. This amounts to breach of contract and unjust enrichment at the expense of my client.",
      "",
      "As per the MSME Act provisions, delayed payments attract mandatory interest at the rate of three times the bank rate notified by RBI, in addition to the principal amount due.",
      "",
      "DEMANDS:",
      "1. Payment of outstanding invoice amount: ₹5,00,000/-",
      "2. Interest on delayed payment as per MSME Act: ₹██,███/-",
      "3. Compensation for business disruption and mental agony: ₹50,000/-",
      "4. Legal notice costs: ₹10,000/-",
      "5. Total amount payable: ₹5,██,███/-",
      "",
      "You are hereby called upon to make full and final payment of the above amount within 15 days from receipt of this notice. Failing compliance, my client shall be compelled to initiate civil proceedings for recovery along with interest, costs, and damages, and/or file complaint before MSME Authority, all at your risk and cost.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of M/s ████████ Pvt. Ltd.",
    ],
  },

  "unpaid-salary": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR NON-PAYMENT OF SALARY AND WRONGFUL TERMINATION",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "The Managing Director",
      "M/s ████ Private Limited",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Recovery of Unpaid Salary and Notice Period Compensation",
      "",
      "Dear Sir,",
      "",
      "Under instructions from my client Mr./Ms. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice for recovery of unpaid salary and statutory dues.",
      "",
      "My client was employed with your company as ████████ from ████████ to ████████ as per the appointment letter dated ████████, with a monthly salary of ₹████████.",
      "",
      "My client states that they entered into a legally binding employment contract dated ████████ which expressly stipulated that employment could not be terminated by either party without serving a prior written notice of ninety (90) days.",
      "",
      "My client tendered resignation on ████████ citing personal reasons and expressly conveyed willingness to serve the mandatory notice period of 90 days in strict compliance with the contract terms.",
      "",
      "However, instead of adhering to the contract terms, your company immediately accepted the resignation and relieved my client on ████████, treating it as the last working day, in direct contravention of the 90-day notice period clause.",
      "",
      "Since my client was ready and willing to serve the entire notice period, your company is legally obligated to compensate my client with full salary and benefits for the entire 90-day notice period. Failure to do so constitutes breach of contract and unfair labor practice.",
      "",
      "Additionally, your company has failed to pay the following statutory dues:",
      "• Salary for the period ████████ to ████████: ₹████████",
      "• Notice period compensation (90 days): ₹████████",
      "• Pending reimbursements: ₹██,███",
      "• Gratuity (if applicable): ₹██,███",
      "",
      "DEMANDS:",
      "1. Three months' notice period salary: ₹████████",
      "2. Unpaid salary and dues: ₹████████",
      "3. Compensation for mental agony and harassment: ₹50,000/-",
      "4. Legal notice costs: ₹10,000/-",
      "5. Total sum payable: ₹██,██,███/- with 12% interest per annum",
      "",
      "You are hereby called upon to pay the aforesaid amount within 7 days from receipt of this notice. Failing compliance, my client shall be constrained to file complaint before Labour Commissioner and/or initiate civil suit for recovery, all at your risk, cost, and consequences.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  divorce: {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR DIVORCE UNDER SECTION 13 OF HINDU MARRIAGE ACT, 1955",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mrs./Mr. ████████",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Seeking Divorce by Mutual Consent / Contested Divorce",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client Mr./Ms. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice intimating intention to seek dissolution of marriage.",
      "",
      "My client and you were lawfully married on ████████ at ████████ in accordance with Hindu rites and customs, in the presence of family and well-wishers. Out of this wedlock, one daughter/son was born.",
      "",
      "Subsequent to the marriage, you and my client established your matrimonial home at ████████ and cohabited there as husband and wife.",
      "",
      "My client states that while the initial years of the marriage were amicable, the relationship has, over the past several years, unfortunately and progressively deteriorated. This decline has not been a temporary phase but rather a consistent and painful erosion of the foundational elements of the marital partnership.",
      "",
      "It has become profoundly evident that a significant and widening emotional and communicative gulf has formed between you and my client. Persistent and fundamental disagreements on core aspects of life have become regular occurrences, indicating a foundational lack of mutual understanding and shared vision essential for any marital relationship to survive.",
      "",
      "My client states that numerous sincere attempts to address these concerns, initiate constructive dialogue, and find a viable path toward reconciliation have regrettably proven unsuccessful, leading to the conclusion that such differences are irreconcilable.",
      "",
      "As a direct consequence of this complete breakdown in the marital relationship, you and my client have been living separately and apart for approximately ████ years. This prolonged separation serves as clear and legally significant testament that the marital bond is broken and the relationship has ceased to exist in any meaningful sense.",
      "",
      "Throughout this period, my client has continued to honor financial responsibilities towards you and your daughter/son, bearing living and household expenses despite the absence of a marital relationship.",
      "",
      "The cumulative effect of irreconcilable differences, total erosion of mutual affection, and extended uninterrupted physical separation has rendered the marriage irretrievably broken with no realistic prospect for reconciliation.",
      "",
      "To continue this marriage in name only would serve no constructive purpose and would only prolong unnecessary mental and emotional hardship for both parties.",
      "",
      "DEMANDS:",
      "1. Come forward for discussion to execute mutual consent divorce deed within 15 days",
      "2. Finalize terms regarding custody, maintenance, and property settlement amicably",
      "3. Cooperate in filing joint divorce petition before the Family Court",
      "",
      "Should you fail to respond or indicate unwillingness to resolve this matter through mutual consent, my client shall be compelled to institute contested divorce proceedings on grounds of cruelty/desertion/adultery under Section 13 of Hindu Marriage Act, 1955. In such event, you shall be responsible for all legal costs and consequences.",
      "",
      "This Notice is issued in good faith with sincere hope that the matter may be resolved amicably without prolonged litigation.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  maintenance: {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR MAINTENANCE UNDER SECTION 125 OF CrPC",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr. ████████",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice Seeking Maintenance under Section 125 of CrPC",
      "",
      "Dear Sir,",
      "",
      "Under instructions from my client Mrs. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice claiming monthly maintenance under Section 125 of the Code of Criminal Procedure, 1973.",
      "",
      "My client and you were lawfully married on ████████ as per Hindu rites and customs. Out of this wedlock, two children were born, namely ████████ (aged ██ years) and ████████ (aged ██ years).",
      "",
      "After marriage, my client and the children have been residing with you in the matrimonial home at ████████. My client has been a devoted wife and mother, taking care of the household and children's upbringing.",
      "",
      "My client states that despite being legally married and having legitimate right to maintenance, you have willfully neglected and refused to maintain my client and the children. You have failed to provide adequate financial support for basic necessities including food, clothing, shelter, medical care, and children's education.",
      "",
      "My client has no independent source of income and is entirely dependent on you for her and the children's survival and sustenance. Your refusal to provide maintenance has placed my client and minor children in acute financial distress and hardship.",
      "",
      "Under Section 125 of CrPC, it is your statutory and moral duty to maintain your wife and minor children who are unable to maintain themselves. Your willful neglect amounts to cruelty and abandonment of family responsibilities.",
      "",
      "My client's reasonable monthly expenses are estimated as follows:",
      "• Household expenses (rent, utilities, groceries): ₹25,000/-",
      "• Children's school fees and education: ₹20,000/-",
      "• Medical and healthcare expenses: ₹10,000/-",
      "• Clothing and miscellaneous: ₹10,000/-",
      "• Total monthly requirement: ₹65,000/-",
      "",
      "Given your financial capacity and monthly income of approximately ₹████████, you are well capable of providing maintenance of ₹65,000/- per month to my client and the children.",
      "",
      "DEMANDS:",
      "1. Pay monthly maintenance of ₹65,000/- to my client and children with effect from ████████",
      "2. Clear all pending arrears of maintenance for past ██ months: ₹████████",
      "3. Provide separate residence or pay house rent of ₹██,███/- monthly",
      "4. Bear all medical and education expenses of children",
      "",
      "You are hereby called upon to comply with the above demands within 15 days from receipt of this notice. Failing compliance, my client shall be compelled to file maintenance petition under Section 125 CrPC before the Magistrate Court, seeking interim and permanent maintenance along with arrears, all at your risk and cost.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  cruelty: {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR CRUELTY, HARASSMENT AND DEMAND FOR MAINTENANCE",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr./Mrs. ████████",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Cruelty, Mental and Physical Harassment",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client Mrs./Mr. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice regarding acts of cruelty, harassment, and domestic violence.",
      "",
      "My client and you were lawfully married on ████████ as per Hindu rites and customs. After marriage, my client moved to your matrimonial home at ████████.",
      "",
      "My client states that from the very beginning of the marriage, you along with your family members have subjected my client to severe physical, mental, emotional, and economic abuse, harassment, and cruelty.",
      "",
      "The acts of cruelty committed by you include:",
      "• Frequent physical assault and battery causing injuries",
      "• Continuous verbal abuse, insults, and humiliation",
      "• Persistent harassment and demand for additional dowry",
      "• Threats to life and causing mental trauma",
      "• Denial of basic necessities including food and clothing",
      "• Restricting freedom of movement and communication",
      "• Economic abuse by denying access to financial resources",
      "",
      "On ████████, you physically assaulted my client causing grievous injuries including ████████, for which medical treatment was taken at ████████ Hospital. Medico-legal case bearing No. ████████ was registered and medical reports are on record.",
      "",
      "You and your family members have been persistently demanding additional dowry of ₹████████ and ████████ [gold/vehicle/property], and have subjected my client to mental and physical torture for not fulfilling these illegal demands.",
      "",
      "Such conduct constitutes 'cruelty' under Section 13(1)(ia) of Hindu Marriage Act, 1955 and 'domestic violence' under Section 3 of Protection of Women from Domestic Violence Act, 2005. It also amounts to criminal offences under Section 498A IPC (Cruelty by husband and relatives) and Dowry Prohibition Act, 1961.",
      "",
      "My client is in imminent danger and fear for life and safety. The continued harassment, cruelty, and domestic violence have caused severe mental trauma, depression, and anxiety to my client.",
      "",
      "DEMANDS:",
      "1. Immediately cease and desist from all acts of violence, cruelty, and harassment",
      "2. Allow my client to reside peacefully in the shared household without interference",
      "3. Return all stridhan articles and jewelry belonging to my client valued at ₹████████",
      "4. Pay monthly maintenance of ₹50,000/- for sustenance and medical expenses",
      "5. Pay compensation of ₹10,00,000/- for physical injuries, mental trauma, and damages",
      "",
      "You are hereby called upon to comply with the above demands within 7 days from receipt of this notice. Failing compliance, my client shall be constrained to:",
      "• File complaint under Section 498A IPC and Dowry Prohibition Act",
      "• File domestic violence petition under DV Act, 2005",
      "• Initiate divorce proceedings on grounds of cruelty",
      "• All at your risk, cost, and legal consequences",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  "tenant-eviction": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR EVICTION OF TENANT AND VACATION OF PREMISES",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr./Ms. ████████ (Tenant)",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Eviction and Vacation of Premises",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client (Landlord), I, the undersigned advocate, hereby serve upon you this Legal Notice for eviction and vacation of premises.",
      "",
      "My client is the absolute owner and lawful landlord of the property bearing No. ████████, situated at ████████, having acquired the same through registered Sale Deed dated ████████.",
      "",
      "You were inducted as a tenant in the said premises vide Rent Agreement dated ████████ at a monthly rent of ₹████████, which was later revised to ₹20,000/- per month from ████████.",
      "",
      "My client states that you have committed serious breach of the tenancy terms by:",
      "• Failing to pay rent for the past 12 months, accumulating arrears of ₹2,40,000/-",
      "• Despite several oral and written reminders, willfully defaulting on rent payments",
      "• Causing substantial damage to the property including broken fixtures and unauthorized alterations",
      "• Violating tenancy agreement which expressly prohibited alterations without landlord's consent",
      "• Subletting portions of the premises without landlord's permission",
      "",
      "Further, my client now requires vacant possession of the premises for bona fide personal use as my client's son is getting married in ████████ and requires the premises for setting up his matrimonial home.",
      "",
      "My client has genuine and bona fide need for the premises and your continued occupation is causing severe hardship to my client and his family.",
      "",
      "My client has made repeated requests for payment of rent arrears and vacation of the premises through letters dated ████████, ████████, and ████████, but you have deliberately avoided all communications and continue to occupy the property illegally without payment of rent.",
      "",
      "Your continued occupation without payment of rent amounts to trespass and unauthorized possession. You have lost all rights of a tenant due to non-payment of rent and breach of tenancy terms.",
      "",
      "DEMANDS:",
      "1. Immediately pay all outstanding rent arrears of ₹2,40,000/- (Rupees Two Lakh Forty Thousand Only) for the period ████████ to ████████, along with interest at 12% per annum",
      "2. Vacate and hand over peaceful and vacant possession of the premises within thirty (30) days from receipt of this Notice, in the same condition as it was let out, fair wear and tear excepted",
      "3. Pay compensation for damages caused to the property amounting to ₹50,000/- and bear the cost of repairs and restoration",
      "4. Remove all your belongings and hand over all keys",
      "",
      "Failing compliance, my client shall be constrained to initiate eviction proceedings under Rent Control Act and file civil suit for possession, claiming:",
      "• Mesne profits at ₹40,000/- per month from the date of notice",
      "• Damages and compensation",
      "• Cost of litigation",
      "• All at your risk and cost",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of Landlord",
    ],
  },

  "rent-arrears": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE FOR RECOVERY OF RENT ARREARS",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "Mr./Ms. ████████ (Tenant)",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Recovery of Rent Arrears and Unpaid Dues",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client (Landlord), I, the undersigned advocate, hereby serve upon you this Legal Notice demanding payment of rent arrears.",
      "",
      "My client is the lawful owner of the property situated at ████████ which was let out to you vide Rent Agreement dated ████████ at a monthly rent of ₹████████.",
      "",
      "As per the terms of the Rent Agreement:",
      "• Monthly rent is payable on or before 5th of every month",
      "• Late payment attracts interest at 2% per month",
      "• Continuous default for 3 months entitles landlord to terminate tenancy",
      "",
      "My client states that you have willfully and deliberately defaulted in payment of rent for the past 18 months from ████████ to ████████, despite repeated oral and written reminders.",
      "",
      "Calculation of Rent Arrears:",
      "• Monthly rent: ₹20,000/-",
      "• Number of months in default: 18 months",
      "• Total rent arrears: ₹3,60,000/-",
      "• Late payment interest @ 2% per month: ₹1,29,600/-",
      "• Maintenance charges unpaid: ₹36,000/-",
      "• Electricity and water bills unpaid: ₹24,500/-",
      "• Total outstanding dues: ₹5,50,100/-",
      "",
      "My client has sent multiple reminders through letters dated ████████, ████████, and ████████ and made personal visits, but you have been avoiding payment on one pretext or another.",
      "",
      "Your willful default in rent payment amounts to breach of tenancy agreement and renders you liable for eviction and recovery proceedings.",
      "",
      "DEMANDS:",
      "1. Immediately pay total outstanding rent arrears and dues of ₹5,50,100/- (Rupees Five Lakh Fifty Thousand One Hundred Only)",
      "2. Resume regular monthly rent payments from ████████ onwards",
      "3. Pay interest on delayed payment at 18% per annum till full and final payment",
      "4. Clear all pending utility bills and maintenance charges",
      "",
      "You are hereby called upon to make full payment within 15 days from receipt of this notice. Failing compliance, my client shall be constrained to:",
      "• Initiate eviction proceedings under Rent Control Act",
      "• File civil suit for recovery of rent arrears with interest and costs",
      "• Claim mesne profits at market rate of ₹40,000/- per month",
      "• All at your risk, cost, and consequences",
      "",
      "Take notice that continued default may result in termination of tenancy and forcible eviction through court orders.",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of Landlord",
    ],
  },

  "builder-delay": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE TO BUILDER UNDER RERA FOR DELAY IN POSSESSION",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "M/s ████ Developers Private Limited",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Delay in Possession and Breach of Buyer-Builder Agreement",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client Mr./Ms. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice under the Real Estate (Regulation and Development) Act, 2016 (RERA).",
      "",
      "My client states that they booked an apartment in your project '████████' located at ████████ vide Booking Application dated ████████ and paid booking amount of ₹████████.",
      "",
      "Subsequently, my client entered into a Buyer-Builder Agreement dated ████████ for purchase of Flat No. ████, Tower ████, admeasuring ████ sq.ft. (super built-up area) for a total consideration of ₹████████.",
      "",
      "As per Clause ██ of the Agreement, possession of the flat was to be handed over by ████████ with a grace period of 6 months, making the due date of possession ████████.",
      "",
      "My client has duly complied with all payment obligations and paid total amount of ₹████████ (███% of agreement value) as per the payment schedule, which has been received and acknowledged by you without demur.",
      "",
      "However, despite the agreed possession date having lapsed over ███ months ago, you have failed and neglected to hand over possession of the flat. The project is still incomplete with substantial construction work pending.",
      "",
      "Your continued delay in possession amounts to:",
      "• Breach of Buyer-Builder Agreement dated ████████",
      "• Violation of Section 18 of RERA Act, 2016",
      "• Deficiency in service under Consumer Protection Act, 2019",
      "",
      "Due to inordinate delay, my client has suffered:",
      "• Financial loss due to continued rent payment: ₹████████",
      "• Loss of rental income from the flat: ₹████████",
      "• Mental agony, harassment, and emotional distress",
      "• Inability to shift to own house as planned",
      "",
      "As per Section 18 of RERA Act, the buyer is entitled to:",
      "• Interest on amounts paid at the rate prescribed by RERA Authority",
      "• Compensation for every month of delay",
      "• Option to seek refund with interest or insist on possession with compensation",
      "",
      "Calculation of Compensation:",
      "• Amount paid to builder: ₹████████",
      "• Delay period: ███ months (from ████████ to till date)",
      "• Interest as per RERA @ ██% per annum: ₹████████",
      "• Compensation for delay @ ₹10 per sq.ft. per month: ₹████████",
      "• Mental agony and harassment: ₹5,00,000/-",
      "• Total compensation due: ₹████████",
      "",
      "DEMANDS:",
      "1. Immediately hand over possession of the flat in completed condition with Occupation Certificate within 30 days",
      "2. Pay compensation for delay as per RERA provisions: ₹████████",
      "3. Pay additional compensation for mental agony: ₹5,00,000/-",
      "4. Alternatively, refund entire amount paid with interest if unable to give possession",
      "",
      "You are hereby called upon to comply within 15 days from receipt of this notice. Failing compliance, my client shall be constrained to:",
      "• File complaint before RERA Authority under Section 31",
      "• File consumer complaint before Consumer Forum",
      "• Initiate civil suit for specific performance and damages",
      "• All at your risk, cost, and consequences",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },

  "consumer-complaint": {
    date: "16th December, 2025",
    title: "LEGAL NOTICE UNDER CONSUMER PROTECTION ACT, 2019",
    bodyParagraphs: [
      "WITHOUT PREJUDICE",
      "",
      "To,",
      "M/s ████ Limited",
      "████████████████",
      "████████, ██████ - ██████",
      "",
      "Sub: Legal Notice for Deficiency in Service and Unfair Trade Practice",
      "",
      "Dear Sir/Madam,",
      "",
      "Under instructions from my client Mr./Ms. ████████, I, the undersigned advocate, hereby serve upon you this Legal Notice under the Consumer Protection Act, 2019.",
      "",
      "My client is a consumer who purchased/availed ████████ [goods/services] from your company on ████████ vide Invoice/Receipt No. ████████ for a total consideration of ₹████████.",
      "",
      "At the time of purchase, your representatives made the following representations and assurances:",
      "• ████████ [Product features/quality standards]",
      "• ████████ [Service specifications/delivery timeline]",
      "• ████████ [Warranty/after-sales support]",
      "",
      "Relying on these representations, my client made full payment of ₹████████ and expected to receive goods/services as promised.",
      "",
      "However, my client has suffered deficiency in service and unfair trade practice as follows:",
      "• The product/service delivered is defective/deficient and does not match the promised specifications",
      "• ████████ [Specific defects/problems encountered]",
      "• Your company has failed to provide after-sales service and honor warranty commitments",
      "• Despite multiple complaints registered on ████████, ████████, and ████████, no satisfactory resolution has been provided",
      "",
      "My client raised complaints through:",
      "• Email to customer care dated ████████",
      "• Written complaint submitted at branch office on ████████",
      "• Multiple phone calls to customer service helpline",
      "• Consumer forum grievance portal registration No. ████████",
      "",
      "Despite all efforts, your company has deliberately ignored and neglected my client's genuine grievances, causing immense harassment, mental agony, and financial loss.",
      "",
      "Your acts constitute:",
      "• Deficiency in service under Section 2(11) of Consumer Protection Act, 2019",
      "• Unfair trade practice under Section 2(47) of the Act",
      "• Breach of contract and warranty obligations",
      "",
      "Due to your deficiency in service, my client has suffered:",
      "• Financial loss of ₹████████ [amount paid for defective goods/services]",
      "• Additional expenses of ₹████████ for alternate arrangements",
      "• Loss of time, effort, and opportunity",
      "• Severe mental agony, harassment, and emotional distress",
      "",
      "DEMANDS:",
      "1. Replace the defective product with a new one of proper quality and specifications",
      "   OR Refund entire amount paid: ₹████████",
      "2. Pay compensation for deficiency in service and unfair trade practice: ₹5,00,000/-",
      "3. Pay compensation for mental agony and harassment: ₹2,00,000/-",
      "4. Pay litigation costs and expenses: ₹50,000/-",
      "5. Total amount payable: ₹████████",
      "",
      "You are hereby called upon to comply with the above demands within 15 days from receipt of this notice and provide satisfactory resolution to my client's genuine grievances.",
      "",
      "Failing compliance, my client shall be compelled to file consumer complaint before the appropriate Consumer Forum under Section 35 of Consumer Protection Act, 2019, claiming:",
      "• Refund of amount paid with interest",
      "• Compensation for deficiency in service",
      "• Compensation for mental agony and harassment",
      "• Punitive damages for unfair trade practice",
      "• Cost of litigation",
      "• All at your risk, cost, and consequences",
      "",
      "Yours faithfully,",
      "████████ (Advocate)",
      "On behalf of My Client",
    ],
  },
};

/**
 * Get real sample notice content by slug
 */
export function getRealSampleNotice(slug: string): SampleNoticeContent | undefined {
  return realSampleNotices[slug];
}

/**
 * Get all available real sample notice types
 */
export function getAllRealSampleNoticeTypes(): string[] {
  return Object.keys(realSampleNotices);
}
